namespace SysCondaWizard;

/// <summary>
/// Generates the Windows PowerShell backup script that mirrors the Linux
/// sysconda_backup.sh cron job. Called during install to write backup_win.ps1.
/// </summary>
public static class BackupScriptGenerator
{
    public static string Generate(WizardConfig cfg)
    {
        // $$""" means only {{expr}} is C# interpolation.
        // Single { and } are literal — perfect for PowerShell script bodies.
        return $$"""
# ============================================================
#  sys.conda — pg_dump backup script (Windows native)
#  Auto-generated by SysCondaWizard. Do not edit manually.
#  Replaces Linux cron + sysconda_backup.sh
# ============================================================

$ErrorActionPreference = "Stop"

# ── Config ───────────────────────────────────────────────────
$BACKUP_DIR  = "{{EscapePs(cfg.BackupDirectory)}}"
$LOG_FILE    = Join-Path $BACKUP_DIR "backup.log"
$PGDUMP      = "{{EscapePs(cfg.PgDumpPath)}}"
$KEEP_FILES  = {{cfg.KeepFiles}}

$DB_HOST     = "{{cfg.DbHost}}"
$DB_PORT     = "{{cfg.DbPort}}"
$DB_NAME     = "{{cfg.DbName}}"
$DB_USER     = "{{cfg.DbUser}}"
$DB_PASS     = "{{EscapePs(cfg.DbPassword)}}"

# ── Helpers ──────────────────────────────────────────────────
function Log([string]$msg) {
    $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $line = "[$ts] $msg"
    Write-Host $line
    Add-Content -Path $LOG_FILE -Value $line -Encoding UTF8
}

# ── Main ─────────────────────────────────────────────────────
try {
    if (-not (Test-Path $BACKUP_DIR)) {
        New-Item -ItemType Directory -Path $BACKUP_DIR -Force | Out-Null
    }

    $DATE     = Get-Date -Format "yyyy-MM-ddTHH-mm-ss"
    $FILENAME = Join-Path $BACKUP_DIR "backup_cron_${DATE}.dump"

    Log "Starting cron backup: $FILENAME"

    # Set password via env var (same as PGPASSWORD on Linux)
    $env:PGPASSWORD = $DB_PASS

    & "$PGDUMP" `
        -h $DB_HOST `
        -p $DB_PORT `
        -U $DB_USER `
        -F c `
        --data-only `
        $DB_NAME `
        --file="$FILENAME"

    if ($LASTEXITCODE -ne 0) {
        throw "pg_dump exited with code $LASTEXITCODE"
    }

    # Validate size (> 512 bytes)
    $size = (Get-Item $FILENAME).Length
    if ($size -lt 512) {
        Remove-Item $FILENAME -Force
        throw "Dump too small (${size} bytes) — aborting."
    }

    # ── Rotate: keep last N files ─────────────────────────────
    Get-ChildItem -Path $BACKUP_DIR -Filter "backup_cron_*.dump" |
        Sort-Object LastWriteTime -Descending |
        Select-Object -Skip $KEEP_FILES |
        Remove-Item -Force

    # ── Write last-backup timestamp ───────────────────────────
    $ts = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
    Set-Content -Path (Join-Path $BACKUP_DIR ".last_backup") -Value $ts -Encoding UTF8

    $kb = [math]::Round($size / 1024, 1)
    Log "SUCCESS: $FILENAME — ${kb} KB"
    exit 0
}
catch {
    Log "ERROR: $_"
    if (Test-Path variable:FILENAME) { Remove-Item $FILENAME -ErrorAction SilentlyContinue }
    exit 1
}
finally {
    $env:PGPASSWORD = $null
}
""";
    }

    private static string EscapePs(string s) => s.Replace("'", "''").Replace("\"", "`\"");
}